spring.application.name=miWeb
# Puerto donde escucha el servidor una vez se inicie
server.port=8084

# base de datos MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/proyectoTransversal?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=carlos
spring.datasource.password=clave
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#  JPA (Hibernate)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML

# JWT Configuration
jwt.secret=wUjW8oVz3yDLSFSN6Z3Iks0=3p1zq7NHRoG7h8x9pL+Fw3RzqP1yH9nZyJ4T3eKxMZs=
jwt.expiration=3600000